name: update-docs

on:
  push:
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 16
      - name: Checkout repository
        uses: actions/checkout@v3
      - name: Yarn init
        run: yarn
      - name: Generate types
        run: yarn types
      - name: Generate with typedoc 
        run: yarn docs
      - name: Commit updated docs
        uses: EndBug/add-and-commit@v9.1.0
        with:
          default_author: github_actions
          message: "update docs"
          add: docs
